name: NextJS

on:
  push:
    branches: [main, master]

jobs:
  build:
  runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
  with:
    node-version: 18

    -r un: npm ci
    - run: npx nextjs install --with-deps
    - run: npx nextjs start
